### ISSUE TITLE
Degree becomes negative after multiplication and addition.

### ISSUE THREAD

**Issue by JoD** [StephanGocht/VeriPB#15]
See line 3958 in `tracelog.txt`, which was obtained by  tracelog.txt by running
```veripb tmp.opb proof.log --trace``` on attached files.
[files.zip](https://github.com/StephanGocht/VeriPB/files/4103674/files.zip)

**Comment by StephanGocht** [comment]
you are reaching overflows which is currently undefined behavior.

**Comment by JoD** [comment]
The addition of the option `--arbitraryPrecision` fixes this issue, and suffices for my current needs.
